sudo: false

language: python

python:
    - 3.5
    - nightly


before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
    - pip install --upgrade pytest pylama pip setuptools wheel --quiet
    - pip install .

before_script: rm --recursive --force --verbose *.py[cod]

script:
  - pytest tests/
#  - pylama anglerfish/*.py


after_script: true

after_success: true

after_failure: true

notifications:
    email:
        recipients: juancarlospaco@gmail.com
        on_success: change
        on_failure: always

cache: apt
